name: generate breakout svg

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  generate-svg:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate SVG
        uses: cyprieng/github-breakout@v1
        with:
          github_username: ${{ github.repository_owner }}

      - name: Prepare files for deployment
        run: |
          mkdir -p dist
          cp output/light.svg dist/breakout-light.svg
          cp output/dark.svg dist/breakout-dark.svg

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: github-breakout
          build_dir: dist
          clean: false  # <--- Added here to keep existing files in the branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
