name: generate pacman game

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      # --- FETCH EXISTING GAMES ---
      - name: Checkout output branch
        uses: actions/checkout@v4
        with:
          ref: output
          path: dist
        continue-on-error: true

      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # The pacman action creates its own 'dist' folder, so we just move it
      - name: Move pacman to merged dist
        run: |
          cp -r output/* dist/ || true

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          clean: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
